// Generated by scripts/generate-types.ts; do not edit directly.

import type { TrustedExtensionContext } from "./kaede-lib.js";

export type TrustedPluginContext = TrustedExtensionContext;

declare global {
  const scopedThis: TrustedPluginContext;
}

export {};
