// Generated by dts-bundle-generator v9.5.1
// Post-processed by scripts/generate-types.ts; do not edit directly.
// Ark 1.0 declaration snapshot: commit 928f1f361abaa4d7204de0bb53dd7b916b04d45b; SHA-256 79f17ec644dc0e8b23ffe246b71637083e3f6c2172acc8ba7966ef519b31e4db

declare const PERMISSION_CATALOG: {
	readonly "ui/basic": {
		readonly description: "Render basic, non-interactive user interface content.";
		readonly dangerLevel: "low";
		readonly scoped: false;
	};
	readonly "ui/forms/non-credential": {
		readonly description: "Render forms that must not collect credentials or other secrets.";
		readonly dangerLevel: "medium";
		readonly scoped: false;
	};
	readonly "network/http": {
		readonly description: "Send HTTP requests to the explicitly granted origins and methods.";
		readonly dangerLevel: "high";
		readonly scoped: true;
	};
	readonly "storage/internal/read": {
		readonly description: "Read files in storage isolated to this exact plugin principal.";
		readonly dangerLevel: "low";
		readonly scoped: true;
	};
	readonly "storage/internal/write": {
		readonly description: "Write files in storage isolated to this exact plugin principal.";
		readonly dangerLevel: "medium";
		readonly scoped: true;
	};
	readonly "storage/external/read": {
		readonly description: "Read files below explicitly granted absolute filesystem roots.";
		readonly dangerLevel: "high";
		readonly scoped: true;
	};
	readonly "storage/external/write": {
		readonly description: "Write files below explicitly granted absolute filesystem roots.";
		readonly dangerLevel: "critical";
		readonly scoped: true;
	};
	readonly "system/process/spawn": {
		readonly description: "Spawn exact executable paths with exact argument arrays.";
		readonly dangerLevel: "critical";
		readonly scoped: true;
	};
	readonly "system/shell": {
		readonly description: "Execute unrestricted shell commands outside the capability sandbox.";
		readonly dangerLevel: "critical";
		readonly scoped: false;
	};
	readonly "events/subscribe": {
		readonly description: "Subscribe to launcher lifecycle and state-change events.";
		readonly dangerLevel: "low";
		readonly scoped: false;
	};
	readonly "logging/write": {
		readonly description: "Write entries to the launcher log.";
		readonly dangerLevel: "low";
		readonly scoped: false;
	};
};
export type EventSnapshotPrimitive = null | undefined | boolean | number | bigint | string;
declare const EVENT_SNAPSHOT_ARRAY: unique symbol;
export interface EventSnapshotArray extends ReadonlyArray<EventSnapshotValue> {
	readonly [EVENT_SNAPSHOT_ARRAY]?: never;
}
export interface EventSnapshotRecord {
	readonly [key: string]: EventSnapshotValue;
}
export type EventSnapshotValue = EventSnapshotPrimitive | EventSnapshotArray | EventSnapshotRecord;
export type ExtensionEventSnapshot<Type extends string = string> = Readonly<{
	"type": Type;
	"value": EventSnapshotValue;
}>;
export type ExtensionEventListener = (event: ExtensionEventSnapshot) => void;
export type PermissionId = keyof typeof PERMISSION_CATALOG;
export type SimplePermissionId = "ui/basic" | "ui/forms/non-credential" | "system/shell" | "events/subscribe" | "logging/write";
export type HttpMethod = "DELETE" | "GET" | "HEAD" | "OPTIONS" | "PATCH" | "POST" | "PUT";
export type NetworkPermissionRequest = Readonly<{
	"id": "network/http";
	"scope": Readonly<{
		"origins": ReadonlyArray<string>;
		"methods": ReadonlyArray<HttpMethod>;
	}>;
}>;
export type InternalStoragePermissionRequest = Readonly<{
	"id": "storage/internal/read" | "storage/internal/write";
	"scope": Readonly<{
		"directory": "principal";
	}>;
}>;
export type ExternalStoragePermissionRequest = Readonly<{
	"id": "storage/external/read" | "storage/external/write";
	"scope": Readonly<{
		"roots": ReadonlyArray<string>;
	}>;
}>;
export type ProcessExecutableScope = Readonly<{
	"path": string;
	"arguments": ReadonlyArray<string>;
}>;
export type ProcessPermissionRequest = Readonly<{
	"id": "system/process/spawn";
	"scope": Readonly<{
		"executables": ReadonlyArray<ProcessExecutableScope>;
	}>;
}>;
export type ScopedPermissionRequest = NetworkPermissionRequest | InternalStoragePermissionRequest | ExternalStoragePermissionRequest | ProcessPermissionRequest;
export type PermissionRequest = SimplePermissionId | ScopedPermissionRequest;
export type BrokerBytes = ReadonlyArray<number>;
export type BrokerHeaders = ReadonlyArray<Readonly<[
	string,
	string
]>>;
export type NetworkHttpRequest = Readonly<{
	"url": string;
	"method": HttpMethod;
	"headers": BrokerHeaders;
	"body"?: string | BrokerBytes;
}>;
export type NetworkHttpResponse = Readonly<{
	"status": number;
	"statusText": string;
	"headers": BrokerHeaders;
	"body": BrokerBytes;
}>;
export interface NetworkHttpCapability {
	readonly "fetch": (request: NetworkHttpRequest) => Promise<NetworkHttpResponse>;
}
export interface InternalStorageReadCapability {
	readonly "read": (relativePath: string) => Promise<BrokerBytes>;
	readonly "readText": (relativePath: string) => Promise<string>;
}
export interface InternalStorageWriteCapability {
	readonly "write": (relativePath: string, contents: BrokerBytes) => Promise<void>;
	readonly "writeText": (relativePath: string, contents: string) => Promise<void>;
	readonly "remove": (relativePath: string) => Promise<void>;
}
export type ExternalStorageTarget = Readonly<{
	"root": string;
	"relativePath": string;
}>;
export interface ExternalStorageReadCapability {
	readonly "read": (target: ExternalStorageTarget) => Promise<BrokerBytes>;
	readonly "readText": (target: ExternalStorageTarget) => Promise<string>;
}
export interface ExternalStorageWriteCapability {
	readonly "write": (target: ExternalStorageTarget, contents: BrokerBytes) => Promise<void>;
	readonly "writeText": (target: ExternalStorageTarget, contents: string) => Promise<void>;
	readonly "remove": (target: ExternalStorageTarget) => Promise<void>;
}
export type ProcessSpawnRequest = Readonly<{
	"path": string;
	"arguments": ReadonlyArray<string>;
}>;
export type ProcessResult = Readonly<{
	"code": number | null;
	"signal": number | null;
	"stdout": BrokerBytes;
	"stderr": BrokerBytes;
}>;
export interface ProcessHandleCapability {
	readonly "handleId": string;
	readonly "pid": number;
	readonly "kill": () => Promise<void>;
	readonly "wait": () => Promise<ProcessResult>;
}
export interface ProcessSpawnCapability {
	readonly "spawn": (request: ProcessSpawnRequest) => Promise<ProcessHandleCapability>;
}
export type ShellExecuteRequest = Readonly<{
	"command": string;
}>;
export interface ShellCapability {
	readonly "execute": (request: ShellExecuteRequest) => Promise<ProcessResult>;
}
export interface EventSubscribeCapability {
	readonly "subscribe": (listener: ExtensionEventListener) => () => void;
}
export type LogLevel = "debug" | "info" | "warn" | "error";
export interface LoggingCapability {
	readonly "write": (level: LogLevel, message: string, details?: ReadonlyArray<string>) => void;
}
export type PluginCapabilities = Readonly<{
	"ui/basic": import("./ark-of-atrahasis-1.0.js").SafeDocument;
	"ui/forms/non-credential": never;
	"network/http": NetworkHttpCapability;
	"storage/internal/read": InternalStorageReadCapability;
	"storage/internal/write": InternalStorageWriteCapability;
	"storage/external/read": ExternalStorageReadCapability;
	"storage/external/write": ExternalStorageWriteCapability;
	"system/process/spawn": ProcessSpawnCapability;
	"system/shell": ShellCapability;
	"events/subscribe": EventSubscribeCapability;
	"logging/write": LoggingCapability;
}>;
export type PermissionGrant = Readonly<{
	"granted": ReadonlyArray<PermissionId>;
	"denied": ReadonlyArray<PermissionId>;
	"capabilities": Readonly<Partial<PluginCapabilities>>;
}>;
export type SandboxPluginContext = Readonly<Partial<PluginCapabilities>>;
export type RequestPermissions = (permissions: ReadonlyArray<PermissionRequest>) => Promise<PermissionGrant>;
declare global {
	const scopedThis: SandboxPluginContext;
	const requestPermissions: RequestPermissions;
}

export {};
