import path from "node:path";
import { fileURLToPath } from "node:url";

import { generateDtsBundle } from "dts-bundle-generator";

const ARK_DECLARATION_SHA256 = "79f17ec644dc0e8b23ffe246b71637083e3f6c2172acc8ba7966ef519b31e4db";
const ARK_SOURCE_COMMIT = "928f1f361abaa4d7204de0bb53dd7b916b04d45b";
const ARK_PACKAGE_REFERENCE = "import(\"ark-of-atrahasis\")";
const ARK_SNAPSHOT_REFERENCE = "import(\"./ark-of-atrahasis-1.0.js\")";
const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const declarationsEntry = path.resolve(
  repositoryRoot,
  "scripts/declaration-sources/kaede-library.ts",
);
const sandboxDeclarationsEntry = path.resolve(
  repositoryRoot,
  "scripts/declaration-sources/kaede-sandbox.ts",
);
const project = path.resolve(repositoryRoot, "tsconfig.app.json");
const generatedDeclaration = path.resolve(repositoryRoot, "types/kaede-lib.d.ts");
const generatedSandboxDeclaration = path.resolve(repositoryRoot, "types/kaede-sandbox.d.ts");
const generatedTrustedDeclaration = path.resolve(repositoryRoot, "types/kaede-trusted.d.ts");
const arkDeclaration = path.resolve(repositoryRoot, "types/ark-of-atrahasis-1.0.d.ts");
const checkOnly = process.argv.includes("--check");

const TRUSTED_DECLARATION = `// Generated by scripts/generate-types.ts; do not edit directly.

import type { TrustedExtensionContext } from "./kaede-lib.js";

export type TrustedPluginContext = TrustedExtensionContext;

declare global {
  const scopedThis: TrustedPluginContext;
}

export {};
`;

async function sha256(filePath: string): Promise<string> {
  const bytes = await Bun.file(filePath).arrayBuffer();
  const digest = await crypto.subtle.digest("SHA-256", bytes);

  return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join("");
}

function generateDeclaration(entryPoint: string): string {
  const [generated] = generateDtsBundle([{
    "filePath": entryPoint,
    "output"  : { "inlineDeclareGlobals": true },
  }], { "preferredConfigPath": project });

  if (generated === undefined) {
    throw new Error(`dts-bundle-generator did not return output for ${entryPoint}`);
  }

  const bundled = generated.replaceAll("\r\n", "\n");
  const arkReferenceCount = bundled.split(ARK_PACKAGE_REFERENCE).length - 1;

  if (arkReferenceCount === 0) {
    throw new Error("Generated declarations did not contain the expected Ark type references");
  }

  if (bundled.includes("\"@/")) {
    throw new Error("Generated declarations contain a private @/ path alias");
  }

  const rewritten = bundled.replaceAll(ARK_PACKAGE_REFERENCE, ARK_SNAPSHOT_REFERENCE);

  if (rewritten.includes(ARK_PACKAGE_REFERENCE)) {
    throw new Error("Generated declarations still contain bare Ark package references");
  }

  const firstLineEnd = rewritten.indexOf("\n");

  if (firstLineEnd === -1) {
    throw new Error("Generated declarations are missing their generator header");
  }

  const provenance = [
    "// Post-processed by scripts/generate-types.ts; do not edit directly.",
    "// Ark 1.0 declaration snapshot: "
    + `commit ${ARK_SOURCE_COMMIT}; SHA-256 ${ARK_DECLARATION_SHA256}`,
  ].join("\n");

  return `${rewritten.slice(0, firstLineEnd + 1)}${provenance}\n`
    + rewritten.slice(firstLineEnd + 1);
}

async function writeOrCheck(filePath: string, contents: string): Promise<string> {
  if (checkOnly) {
    const checkedInDeclaration = await Bun.file(filePath).text();

    if (checkedInDeclaration !== contents) {
      const relativePath = path.relative(repositoryRoot, filePath);

      throw new Error(`${relativePath} is stale; run bun run generate:types`);
    }
  } else {
    await Bun.write(filePath, contents);
  }

  return sha256(filePath);
}

const arkHash = await sha256(arkDeclaration);

if (arkHash !== ARK_DECLARATION_SHA256) {
  throw new Error(
    `Ark declaration snapshot hash mismatch: expected ${ARK_DECLARATION_SHA256}, got ${arkHash}`,
  );
}

const declaration = generateDeclaration(declarationsEntry);
const sandboxDeclaration = generateDeclaration(sandboxDeclarationsEntry);
const generatedHash = await writeOrCheck(generatedDeclaration, declaration);
const sandboxHash = await writeOrCheck(generatedSandboxDeclaration, sandboxDeclaration);
const trustedHash = await writeOrCheck(generatedTrustedDeclaration, TRUSTED_DECLARATION);

await Bun.write(
  Bun.stdout,
  `Verified Ark ${arkHash}\n`
  + `${checkOnly ? "Checked" : "Generated"} Kaede core ${generatedHash}\n`
  + `${checkOnly ? "Checked" : "Generated"} Kaede sandbox ${sandboxHash}\n`
  + `${checkOnly ? "Checked" : "Generated"} Kaede trusted ${trustedHash}\n`,
);
