name: "Build (Wails)"

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - flake.lock
    branches:
      - nightly
      - beta
      - rc
      - release
    tags:
      - "*"
  workflow_dispatch:

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'App'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'App'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'App'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Swap placeholder exports with actual Wails-only utils
        run: |
          rm -rf ./src/lib/wails
          mv ./src/lib/__wails ./src/lib/wails
        shell: bash

      - name: Build wails
        uses: dAppCore/build@v4.16.0
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          package: false
          STACK: wails3
